from typing import Protocol

from azotea_cli.common.enums import HeaderType, ImageType
from azotea_cli.common.rect import Rect

from .models import Array2Du16, ImageMetadata

class RawPixels(Protocol):
    def r(self, section: Rect | None) -> Array2Du16: ...
    def g1(self, section: Rect | None) -> Array2Du16: ...
    def g2(self, section: Rect | None) -> Array2Du16: ...
    def b(self, section: Rect | None) -> Array2Du16: ...

    def r_black(self) -> int: ...
    def g1_black(self) -> int: ...
    def g2_black(self) -> int: ...
    def b_black(self) -> int: ...


class ImageReader(Protocol):
    def header_type(self) -> HeaderType: ...

    def image_type(self) ->ImageType: ...

    def read_metadata(self, path: str) -> ImageMetadata:
        """returns an instance of ImageMetadata dataclass"""
        ...

    def read_pixels(self, path:  str) -> RawPixels:
        """returns an object that implements the RawPixels interface"""
        ...

__all__ = ["RawPixels", "ImageReader"]
