from typing import Protocol

from .models import (
    CameraForm,
    DefaultOptics,
    DefaultOpticsForm,
    LocationForm,
    ObserverForm,
    RoiForm,
)

# ----------
# Interfaces
# ----------

class IDisplay(Protocol):
    def display(self, text: str) -> None: ...

class IConsentProv(Protocol):
    def review(self) -> str: ...
    def agree(self, agreed: bool) -> None: ...
    def agreed(self) -> bool: ...
    def check_raises(self) -> None: ...

class ILocationProv(Protocol):
    def create(self, form: LocationForm, as_default: bool) -> int: ...
    def update(self, form: LocationForm) -> None: ...
    def set_default_id(self, location_id) -> None: ...
    def get_default_id(self, location_id) -> None: ...

class IObserverProv(Protocol):
    def create_observer_vers(self, form: ObserverForm, as_default: bool) -> None: ...
    def update_observer(self, form: ObserverForm) -> None: ...

class ICameraProv(Protocol):
    def create_camera(self, form: CameraForm, as_default: bool) -> None: ...
    def create_camera_from_image(self, path: str, as_default: bool) -> None: ...


class IOpticsProv(Protocol):
    def save_default_optics(self, form: DefaultOpticsForm) -> None: ...
    def load_default_optics(self) -> DefaultOptics: ...


class IRoiProv(Protocol):
    def create_roi(self, form: RoiForm, as_default: bool) -> None: ...
    def create_roi_from_image(self, path: str,  width: int, height: int, as_default: bool) -> None: ...


__all__ = [
    "IDisplay",
    "IConsentProv",
    "ILocationProv",
    "IObserverProv",
    "ICameraProv",
]
