from typing import Protocol

from .models import (
    CameraForm,
    DefaultOptics,
    DefaultOpticsForm,
    LocationForm,
    ObserverForm,
    RoiForm,
    RoiCenteredForm,
)

# ----------
# Interfaces
# ----------

class IDisplay(Protocol):
    def display(self, text: str) -> None: ...

class IConsentProv(Protocol):
    def review(self) -> str: ...
    def agree(self, agreed: bool) -> None: ...
    def agreed(self) -> bool: ...
    def check_raises(self) -> None: ...

class ILocationProv(Protocol):
    def create(self, form: LocationForm, as_default: bool) -> int: ...
    def update(self, form: LocationForm) -> None: ...
    def set_default(self, location_id) -> None: ...
    def get_default(self) -> int: ...

class IOpticsProv(Protocol):
    def save(self, form: DefaultOpticsForm) -> None: ...
    def load(self) -> DefaultOptics: ...

class IObserverProv(Protocol):
    def create_versioned(self, form: ObserverForm, as_default: bool) -> int: ...
    def update(self, form: ObserverForm) -> None: ...
    def set_default(self, observer_id) -> None: ...
    def get_default(self) -> int: ...

class ICameraProv(Protocol):
    def create(self, form: CameraForm, as_default: bool) -> int: ...
    def create_from_image(self, path: str, optics: DefaultOptics, as_default: bool) -> int: ...
    def set_default(self, camera_id) -> None: ...
    def get_default(self) -> int: ...

class IRoiProv(Protocol):
    def create(self, form: RoiForm, as_default: bool) -> int: ...
    def create_from_image(self, path: str,  form: RoiCenteredForm, optics: DefaultOptics, as_default: bool) -> int: ...
    def set_default(self,roi_id) -> None: ...
    def get_default(self) -> int: ...


__all__ = [
    "IDisplay",
    "IConsentProv",
    "ILocationProv",
    "IObserverProv",
    "ICameraProv",
]
